meta:
  name: 'DKMotd English'
  module: 'DKMotd'
  language:
    name: 'English'
    localizedName: 'English'
    code: 'en'
messages:
  dkmotd.prefix: '&8» &bDKMotd &8|&f'

  dkmotd.error.index.notValid: '${dkmotd.prefix} &e{value} &cis not a valid index'
  dkmotd.error.number.notValid: '${dkmotd.prefix} &e{value} &cis not a valid number'
  dkmotd.error.duration.notValid: '${dkmotd.prefix} &e{value} &cis not a valid duration'
  dkmotd.error.version.notValid: '${dkmotd.prefix} &e{value} &cis not a valid version'
  dkmotd.error.dateFormat.notValid: '${dkmotd.prefix} &e{value} &cis not a valid date format'

  dkmotd.error.motdTemplate.notExists: '${dkmotd.prefix} &cThe motd template &e{name} &cdoes not exists'
  dkmotd.error.motdTemplate.alreadyExists: '${dkmotd.prefix} &cThe motd template &e{template.name} &calready exists'
  dkmotd.error.motdTemplate.deleteNotPossible: '${dkmotd.prefix} &cIt is not possible to delete the motd template &e{template.name}'

  dkmotd.error.joinMessageTemplate.notExists: '${dkmotd.prefix} &cThe join message template &e{name} &cdoes not exists'
  dkmotd.error.joinMessageTemplate.alreadyExists: '${dkmotd.prefix} &cThe join message template &e{template.name} &calready exists'


  dkmotd.command.motd.help: '${dkmotd.prefix} &cInvalid usage of motd command&8:
  &7/motd list
  &7/motd <name> [info]
  &7/motd <name> active
  &7/motd <name> create
  &7/motd <name> delete
  &7/motd <name> name <name>
  &7/motd <name> baseLine <text>
  &7/motd <name> secondLines
  &7/motd <name> versionText <text>
  &7/motd <name> wrongVersionText <text>
  &7/motd <name> supportedVersions
  &7/motd <name> favicon <favicon>
  &7/motd <name> playerInfo'

  dkmotd.command.motd.secondLines.help: '${dkmotd.prefix} &cInvalid usage of motd secondLines command&8:
  &7/motd <name> secondlines add <line>
  &7/motd <name> secondlines remove <index>
  &7/motd <name> secondlines set <line>
  &7/motd <name> secondlines clear'

  dkmotd.command.motd.playerInfo.help: '${dkmotd.prefix} &cInvalid usage of motd playerInfo command&8:
  &7/motd <name> playerInfo add <line>
  &7/motd <name> playerInfo remove <index>
  &7/motd <name> playerInfo set <line>
  &7/motd <name> playerInfo clear'

  dkmotd.command.motd.supportedVersions.help: '${dkmotd.prefix} &cInvalid usage of motd supportedVersions command&8:
  &7/motd <name> supportedVersions add <version>
  &7/motd <name> supportedVersions remove <version>
  &7/motd <name> supportedVersions set <version>
  &7/motd <name> supportedVersions clear'

  dkmotd.command.motd.create: '${dkmotd.prefix} &7You have created the motd template &e{template.name}'

  dkmotd.command.motd.delete: '${dkmotd.prefix} &7You have deleted the motd template &e{template.name}'

  dkmotd.command.motd.info: '${dkmotd.prefix} &7Motd template &e{template.name} &7info
  &8» &7Base line&8: &e{template.baseLine}
  &8» &7Version text&8: &e{template.versionText}
  &8» &7Wrong version text&8: &e{template.wrongVersionText}
  &8» &7Supported versions&8: @for("version" in {template.supportedVersions}, ${dkmotd.command.motd.info.supportedVersions},",", ",")
  &8» &7Favicon&8: &e{template.favicon}
  &8» &7Second lines&8: @for("line" in {template.secondLines}, ${dkmotd.command.motd.info.secondLines},"\n", "\n")
  &8» &7Player info&8: @for("line" in {template.playerInfo}, ${dkmotd.command.motd.info.playerInfo},"\n", "\n")'
  dkmotd.command.motd.info.secondLines: ' &8- &e{line}'
  dkmotd.command.motd.info.supportedVersions: ' &8- &e{version}'
  dkmotd.command.motd.info.playerInfo: ' &8- &e{line}'

  dkmotd.command.motd.list: '${dkmotd.prefix} &7Motd templates&8: @for("template" in {templates}, ${dkmotd.command.motd.list.loop},"\n", "\n")'
  dkmotd.command.motd.list.loop: ' &8- &e{template.name}'

  dkmotd.command.motd.name: '${dkmotd.prefix} &7You have changed the name to &e{template.name}'
  dkmotd.command.motd.baseLine: '${dkmotd.prefix} &7You have changed the baseLine to &e{template.baseLine}'
  dkmotd.command.motd.versionText: '${dkmotd.prefix} &7You have changed the version text to &e{template.versionText}'
  dkmotd.command.motd.wrongVersionText: '${dkmotd.prefix} &7You have changed the wrong version text to &e{template.wrongVersionText}'
  dkmotd.command.motd.active: '${dkmotd.prefix} &7You have changed the active motd template to &e{template.name}'

  dkmotd.command.motd.secondLines.add: '${dkmotd.prefix} &7You have added a second line'
  dkmotd.command.motd.secondLines.set: '${dkmotd.prefix} &7You have set the second lines'
  dkmotd.command.motd.secondLines.remove: '${dkmotd.prefix} &7You have removed a second line'
  dkmotd.command.motd.secondLines.clear: '${dkmotd.prefix} &7You have cleared the second lines'

  dkmotd.command.motd.playerInfo.add: '${dkmotd.prefix} &7You have added a player info'
  dkmotd.command.motd.playerInfo.set: '${dkmotd.prefix} &7You have set the player info'
  dkmotd.command.motd.playerInfo.remove: '${dkmotd.prefix} &7You have removed a player info'
  dkmotd.command.motd.playerInfo.clear: '${dkmotd.prefix} &7You have cleared the player info'

  dkmotd.command.motd.supportedVersions.add: '${dkmotd.prefix} &7You have added a supported version'
  dkmotd.command.motd.supportedVersions.set: '${dkmotd.prefix} &7You have set the supported version'
  dkmotd.command.motd.supportedVersions.remove: '${dkmotd.prefix} &7You have removed a supported version'
  dkmotd.command.motd.supportedVersions.clear: '${dkmotd.prefix} &7You have cleared the supported version'


  dkmotd.command.maintenance.help: '${dkmotd.prefix} &cInvalid usage of maintenance command&8:
  &7/maintenance active
  &7/maintenance info
  &7/maintenance timeout <timeout>
  &7/maintenance duration <duration>'
  dkmotd.command.maintenance.active.on: '${dkmotd.prefix} &7You have turned &aon &7the maintenance'
  dkmotd.command.maintenance.active.off: '${dkmotd.prefix} &7You have turned &coff &7the maintenance'
  dkmotd.command.maintenance.timeout: '${dkmotd.prefix} &7You have changed the maintenance timeout to &e{maintenance.formattedTimeout}'
  dkmotd.command.maintenance.info: '${dkmotd.prefix} &cMaintenance info
  &8» &7Active&8: &e{maintenance.active}
  &8» &7Timeout&8: &e{maintenance.formattedTimeout}'


  dkmotd.command.joinMessage.help: '${dkmotd.prefix} &cInvalid usage of joinmessage command&8:
  &7/joinmessage list
  &7/joinmessage <name> [info]
  &7/joinmessage <name> active
  &7/joinmessage <name> create
  &7/joinmessage <name> delete
  &7/joinmessage <name> name <name>
  &7/joinmessage <name> baseMessage <text>
  &7/joinmessage <name> secondMessages'
  dkmotd.command.joinMessage.create: '${dkmotd.prefix} &7You have created the join message template &e{template.name}'

  dkmotd.command.joinMessage.delete: '${dkmotd.prefix} &7You have deleted the join message template &e{template.name}'

  dkmotd.command.joinMessage.info: '${dkmotd.prefix} &7Join message template &e{template.name} &7info
  &8» &7Base message&8: &e{template.baseMessage}
  &8» &7Second messages&8: @for("line" in {template.secondMessages}, ${dkmotd.command.joinMessage.info.secondMessages},"\n", "\n")'
  dkmotd.command.joinMessage.info.secondMessages: ' &8- &e{line}'

  dkmotd.command.joinMessage.list: '${dkmotd.prefix} &7Join message templates&8: @for("template" in {templates}, ${dkmotd.command.joinMessage.list.loop},"\n", "\n")'
  dkmotd.command.joinMessage.list.loop: ' &8- &e{template.name}'

  dkmotd.command.joinMessage.active: '${dkmotd.prefix} &7You have changed the active join message template to &e{template.name}'

  dkmotd.command.joinMessage.name: '${dkmotd.prefix} &7You have changed the name to &e{template.name}'
  dkmotd.command.joinMessage.baseMessage: '${dkmotd.prefix} &7You have changed the baseMessage to &e{template.baseMessage}'

  dkmotd.command.joinMessage.secondMessages.help: '${dkmotd.prefix} &cInvalid usage of motd secondMessages command&8:
  &7/joinmessage <name> secondMessages add <line>
  &7/joinmessage <name> secondMessages remove <index>
  &7/joinmessage <name> secondMessages set <line>
  &7/joinmessage <name> secondMessages clear'

  dkmotd.command.joinMessage.secondMessages.add: '${dkmotd.prefix} &7You have added a second message'
  dkmotd.command.joinMessage.secondMessages.set: '${dkmotd.prefix} &7You have set the second messages'
  dkmotd.command.joinMessage.secondMessages.remove: '${dkmotd.prefix} &7You have removed a second message'
  dkmotd.command.joinMessage.secondMessages.clear: '${dkmotd.prefix} &7You have cleared the second messages'
